### ISSUE TITLE
Bug: {% include img} with blockquote makrdown

### ISSUE THREAD

**Issue by wrlawodms** [teamsecond/teamsecond.github.io#9]
![image](https://user-images.githubusercontent.com/4846884/60491266-5b9c7400-9ce3-11e9-9504-7868a19f3d57.png)

이미지첨부와 마크다운의 blockquote를 같이 사용하면 다음과 같이 </figure>가 출력됩니다.
blockquote를 제거하면 출력되지 않습니다.

**Comment by hgryoo** [comment]
linked PR #13

**Comment by hgryoo** [comment]
fixed
